name: transit
version: 0.8.0
author: Marián Horňák
description: Transit for Dart
homepage: https://github.com/syslo/transit-dart
dependencies:
  crypto: 0.9.0
  msgpack: any
dev_dependencies:
  unittest: any
