name: transit
version: 0.8.2
author: Clean Team <clean@vacuumlabs.com>
description: Transit for Dart
homepage: https://github.com/cleandart/transit-dart
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  msgpack: '>=0.0.4 <0.1.0'
dev_dependencies:
  unittest: any
