name: transit
version: 0.8.3
author: Clean Team <clean@vacuumlabs.com>
description: Transit for Dart
homepage: https://github.com/cleandart/transit-dart
environment:
  sdk: '>=2.13.0 <3.0.0'
dependencies:
  crypto: ^3.0.1
  msgpack_dart: ^1.0.0
dev_dependencies:
  test: ^1.17.10
